### ISSUE TITLE
Using Inpainting errors in the OnnxDiffusersUI interface

### ISSUE THREAD

**Issue by dongzheng9** [Amblyopius/Stable-Diffusion-ONNX-FP16#10]
First of all, thank you author you saved my amd graphics card .No matter what model I use in OnnxDiffusersUI-inpainting, I get an error 
I read https://github.com/azuritecoin/OnnxDiffusersUI#inpainting-fix  
Author says  If inpainting does not work for you, please follow these steps from de_inferno#6407 on discord to fix it.
Within: virtualenv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion_inpaint_legacy.py
Find (likely on line 402): sample=latent_model_input, timestep=np.array([t]), encoder_hidden_states=prompt_embeds
Replace with: sample=latent_model_input, timestep=np.array([t], dtype="float32"), encoder_hidden_states=prompt_embeds
But I can't find these files. What do I do? Thanks again

**Comment by xzuyn** [comment]
if you cant find those files you installed it wrong. can you post your error?

**Comment by xzuyn** [comment]
if you followed the guide from this github page, the file is likely at `sd_env\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion_inpaint_legacy.py` instead

**Comment by dongzheng9** [comment]
> if you cant find those files you likely installed it wrong. can you post your error?

Thank you I found the problem, it was caused by my not using the inpainting model Now it works well
