### ISSUE TITLE
Bad output on Intel A770

### ISSUE THREAD

**Issue by crispysilicon** [Amblyopius/Stable-Diffusion-ONNX-FP16#15]
You wanted to know how it ran on Intel.

![image](https://user-images.githubusercontent.com/89959532/224577255-b25dab64-7e97-418d-8205-83c06893ae99.png)
 
SD 2.1 large, base fp-16 top, base fp-32 bottom. 

I've tried converting an earlier version of SD, changing the steps and guidance scale, always bad output though.

**Comment by Amblyopius** [comment]
Yes, another user was having the same issue. It seems like DirectML is currently not working with Intel drivers.

Unfortunately ONNX Runtime 1.14 has not released for OpenVino either. I hence fear there's no Arc support there either.

Your best bet may be to use Intel extension for PyTorch which in theory gives native support in torch and hence you could run nearly every Stable Diffusion implementation if you find your way around Python. Hopefully the driver issues get fixed soon. If I bump into a cheap way to get an Arc card I might try to figure out what's happening.

**Comment by Amblyopius** [comment]
Would be interesting to know whether the latest drivers changed things for any of you with Arc. Given they did some Direct X fixes, they may have fixed DirectML ...

**Comment by crispysilicon** [comment]
I have tried it, but not yet.

But I do have an open ticket on it that is being worked on, so fingers
crossed.

**Comment by Amblyopius** [comment]
Nice, thanks for letting me know!
