### ISSUE TITLE
0.15.0 breaks conv_sd_to_onnx.py

### ISSUE THREAD

**Issue by woodwardj** [Amblyopius/Stable-Diffusion-ONNX-FP16#22]
load_pipeline_from_original_stable_diffusion_ckpt is now download_from_original_stable_diffusion_ckpt.

Fixing the 2 instances of that appears to be working.

**Comment by Amblyopius** [comment]
I know, fixed it locally already. Will update it in a bit.

**Comment by Amblyopius** [comment]
Uploaded now. It fixes the change in how ckpt are loaded and it imports the attention processor from the desired location (that's 1 warning less).
