### ISSUE TITLE
onnxruntime-directml not supported

### ISSUE THREAD

**Issue by EgShes** [Amblyopius/Stable-Diffusion-ONNX-FP16#23]
onnxruntime-directml is not supported on all the systems. It's not needed for onnx converting but causes the requirements installation failure.

For my system (linux, x64, cuda) I installed onnxruntime-gpu and test-txt2img.py worked just fine.

I suggest to remove this library from requirements.txt and add to README, that pepople should install onnxruntime before test run.

![image](https://user-images.githubusercontent.com/42002290/232230791-15f5ef23-ccf0-4284-9ff1-fe9a4e919a30.png)

**Comment by Amblyopius** [comment]
I can always split the requirements.txt files and have multiple based on the common cases. The scripts can have some detection added to determine the provider. I've got an older laptop that has a GTX 1070. I'll try and fire it up to do some testing. Most users are on Windows/DirectML and others probably (like you) don't struggle too hard with making the necessary changes but I agree it's useful to make it as simple as possible.
