### ISSUE TITLE
Support Long Prompts

### ISSUE THREAD

**Issue by Cydhra** [Amblyopius/Stable-Diffusion-ONNX-FP16#25]
Is there a way to modify the pipeline before converting while still using custom models? Because there are custom pipelines supporting long prompts (see [here](https://github.com/huggingface/diffusers/tree/main/examples/community#long-prompt-weighting-stable-diffusion)), but so far I can't see a way to use those. You have provided your own custom pipelines for ControlNet etc, but those replace the model (as far as I understand, I am not that great with python and diffusers yet)
Is there a way to provide a custom pipeline (or add first-class support for long prompts) while still loading custom models?

**Comment by Amblyopius** [comment]
Hi, we already have the lpw pipeline in ONNXDiffusersUI. Only the demos are not using it. But it's not hard to add it there either, just not as useful. In the future lpw is likely to become the default for all of it (and we'll move to hybrid pipelines that run CLIP on CPU as that gives easy textual embedding support).
